### PR TITLE
Update depth_packet_processor.cpp

### PR DESCRIPTION
**Pull request by vinouz**
Just some split whose sum didn't seem to make 1 (rounding errors accumulating ?)

### CODE REVIEW

**Comment by ofTheo** [comment]
did you notice any bug / issue that this PR solves?
sometime floats are done in a way where it doesn't add up to 1.0 because of float rounding

http://floating-point-gui.de/basic/

**Comment by vinouz** [comment]
yup. I did the computation on a sheet of paper, so no rounding errors of the IEEE754 sort should appear here ;)

It’s just that the coefficients are rounded up decimally and don’t sum to 1.0, be it real or fp.

I also backported the correction to libfreenect2, so anyways it’s gonna end up changed here hopefully ;)

Ah, and thanks for openframeworks, and for fffff.at ;)

**Comment by ofTheo** [comment]
ah okay - didn't realize you were doing it for libfreenect2 as well :) 
your most welcome!!!

**Comment by vinouz** [comment]
yup, did it afterwards ;)

Vincent B., Ph.D
E-mail: vinouz@yahoo.fr
---

The Illiterati Programus Canto 1: A program is a lot like a nose: Sometimes it runs, and sometimes it blows.

**Comment by vinouz** [comment]
The issue with a global coef of the gaussian filter matrix at 0.9999999f would be 5dB of light attenuation every 10 million iterations. Mot much I agree ;)

Vincent B., Ph.D
E-mail: vinouz@yahoo.fr
---

"Classical liberalism (the people are the ultimate authority) is dying a slow death in the face of more-and-more power grabs." - Slashdot comment about a french journalist from TF1 fired for his opinions on HADOPI

**Pull request merged**
