### PR TITLE
Added Support for linux64 and linuxarmv7l

### PR DESCRIPTION
**Pull request by madelinegannon**

### CODE REVIEW

**Comment by ofTheo** [comment]
Thanks @madelinegannon @bakercp !  
Apologies for the slow review and merge.

**Comment by ofTheo** [comment]
Following up - noticed that this PR includes libfreenect2 as a lib. 
Any reason not to keep it as source?

I think it would make Windows support easier if we just had libfreenect2 compiled from source.

**Comment by bakercp** [comment]
(source avoids a lot of issues)

**Comment by ofTheo** [comment]
Thanks @bakercp - my goal is to get this installing easily for Mac/Win/Nix via the PG. So might look at bringing the source back in.  

@madelinegannon I am assuming it won't break anything to use the source.  We could always add excludes in the addons_config.make if needed.

**Pull request merged**
