### PR TITLE
Fix #19 and updated DLLs

### LINKED ISSUE #19: Can't allocate an array of constant size 0 in libfreenect2
Hi, 

I encounter an error when compiling a project with ofxKinectV2 on Windows 10, Visual Studio 2015 and of 0.9.2.

The line 48 of resource.cpp file in libfreenect2 lib cause a "cannot allocate an array of constant size 0" error (C2466) :

```
#ifdef RESOURCES_INC
#include "resources.inc.h"
#else
static ResourceDescriptor resource_descriptors[] = {};
static int resource_descriptors_length = 0;
#endif
```

It seems to be related to [this issue](https://github.com/OpenKinect/libfreenect2/issues/443) in libfreenect2, but it doesn't cause error when compiling libfreenect2 project, because RESOURCES_INC macro is defined so this code is not compiled (and so the error isn't really fixed)

I didn't see any "resources.inc.h" file in the addon, so I don't know if it could be possible to bypass this error, or if I should report this issue to libfreenect team ?

### PR DESCRIPTION
**Pull request by ghost**
I added your fix for #19 and updated the DLLs, which didn't work as I expected. 
These are the one from [here](https://github.com/xlz/libusb/releases/tag/v1.0.20-winiso) (don't know what was wrong with my build, had [this issue](https://github.com/OpenKinect/libfreenect2/issues/471)). 
Hope this one works universally (I don't know if there is much Windows users to test it)

### CODE REVIEW

**Comment by LauraLaureus** [comment]
@BaptisteTheoriz I'm new to OpenFramework and to Kinect v2, can you provide me a guide to the process you did until get the plugin working on Windows?

**Comment by BaptisteTheoriz** [comment]
Hi, sorry for the delay.
I just updated my [repository](https://github.com/BaptisteTheoriz/ofxKinectV2) with a Visual Studio example project and I updated the readme file with instructions about how to install drivers etc. 
I hope that will help you, and @ofTheo can merge them if it matches its needs.

**Comment by LauraLaureus** [comment]
Thank you so much for the update @BaptisteTheoriz  ^^ I'll check it as soon as i finish to study some code that the Kinect SDK has >.<.  

And you don't have to apologize, I understand everyone has a personal life outside Github. ^^

**Comment by LauraLaureus** [comment]
@BaptisteTheoriz I got the error libusb1.0.dll not found at running time. 
Does the .dll that you uploaded work only in Win32? Intel OpenCL needs to compile in x64. 
I did instal the libusbK as you state in the instructions of your fork.

**Comment by mattfelsen** [comment]
Hi @BaptisteTheoriz  & @LauraLaureus. I am trying to get this running but having some issues. I followed the install instructions (libusbK via Zadig, installed CUDA v8, added the env variables) and can get the app to compile. However, I get this exception when running from VS:

```
Exception thrown at 0x00007FFF3DCEA74A (igdrcl64.dll) in example.exe: 0xC0000005: Access violation reading location 0x0000000000000994.

If there is a handler for this exception, the program may be safely continued.
```

Some searching indicated it might be an admin privileges thing, and I noticed that running the app, either as an adminstrator or not, directly out of the File Explorer doesn't produce that exception, but also doesn't work either - I just get a blank window at that point.

I'm running on Win10 with VS2015 on a computer with an Nvidia GTX 1060. Any thoughts on things to look into? I'll probably see if I can get the libfreenect2 running as a starter...next year :) @LauraLaureus what version of CUDA & VS did you get things working with?

Thanks & happy new year y'all!

**Comment by LauraLaureus** [comment]
I haven't working with CUDA for a year, but I think it's different than OpenCL and the statement that trigger that error is from OpenCL because it has the "cl" prefix. 
I don't know if you install CUDA you install together OpenCL, but I only know that OpenCL runs on CUDA based NVIDIA GPU. 

I get the example running using Intel OpenCL, since my GPU is Intel's, on Windows 10 + Visual Studio Community 2015.

Sorry, if i'm not helpful u.u

**Comment by ofTheo** [comment]
@BaptisteTheoriz - I merged in the other PRs from @bakercp @madelinegannon. 
Do you think you could re-submit this or open another PR with the dll fixes for Windows against the current master?

The other PRs added quite a few features the add-on was missing. 

Many thanks!
Theo

**Comment by ofTheo** [comment]
closed #39 should take care of this. master should be windows compatible now thanks to @NickHardeman

**Comment by brunoimbrizi** [comment]
In case anyone runs into the same problem as @mattfelsen with igdrcl64.dll which just happened to me while trying to run ofxKinectV2/example on my laptop:

```
Exception thrown at 0x00007FFF3DCEA74A (igdrcl64.dll) in example.exe: 0xC0000005: Access violation reading location 0x0000000000000994.
```

I managed to solve it by updating the Intel Graphics driver from 21.20.xxx to 26.20.xxx
Device Manager > Display adapters > Intel(R) HD Graphics > Properties > Driver > Update Driver

**Pull request closed without merging**
